# Generated by Django 2.1 on 2018-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlamBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=500)),
                ('my_nickname', models.CharField(max_length=500)),
                ('my_address', models.CharField(max_length=1000)),
                ('my_mobile_number', models.CharField(max_length=20)),
                ('my_email', models.EmailField(max_length=50)),
                ('my_birth_day', models.DateField()),
                ('my_zodiac_sign', models.CharField(max_length=30)),
                ('my_crush', models.CharField(max_length=50)),
                ('my_class_crush', models.CharField(max_length=50)),
                ('my_college_crush', models.CharField(max_length=50)),
                ('my_happiest_moment', models.CharField(max_length=1000)),
                ('my_favourite_dishes', models.CharField(max_length=1000)),
                ('my_favourite_sports', models.CharField(max_length=500)),
                ('my_favourite_places', models.CharField(max_length=500)),
                ('my_favourite_actor', models.CharField(max_length=200)),
                ('my_favourite_actress', models.CharField(max_length=200)),
                ('my_favourite_webiste', models.CharField(max_length=300)),
                ('my_favourite_festival', models.CharField(max_length=300)),
                ('my_favourite_song', models.CharField(max_length=300)),
                ('my_ideal', models.CharField(max_length=150)),
                ('opinion_about_you', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
