# Generated by Django 2.1 on 2018-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='my_class_crush',
        ),
        migrations.RemoveField(
            model_name='slambook',
            name='my_college_crush',
        ),
        migrations.RemoveField(
            model_name='slambook',
            name='my_crush',
        ),
        migrations.AddField(
            model_name='slambook',
            name='being_written_to',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='slambook',
            name='my_crushes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_actor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_actress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_dishes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_festival',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_places',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_song',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_sports',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_favourite_webiste',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_happiest_moment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_ideal',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_nickname',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_zodiac_sign',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='opinion_about_you',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
