# Generated by Django 2.1 on 2018-08-27 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slam', '0002_auto_20180825_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='being_written_to',
        ),
        migrations.AddField(
            model_name='slambook',
            name='being_written_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
