# Generated by Django 2.1 on 2018-08-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0003_auto_20180826_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slambook',
            name='my_birth_day',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_crushes',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slambook',
            name='my_zodiac_sign',
            field=models.CharField(default='', max_length=300),
        ),
    ]
