# Generated by Django 2.1 on 2018-08-27 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slam', '0004_auto_20180826_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='being_written_to',
        ),
        migrations.AddField(
            model_name='slambook',
            name='being_written_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
