# Generated by Django 2.1 on 2018-08-27 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0006_auto_20180826_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slambook',
            name='being_written_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
